### ISSUE TITLE
Allow choice of the mysql protocol

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt-cli#61]
Currently you don't have control over the mysql protocol which disallows you to use flynt-cli in combination with a tcp connection.

**Example Setup**

1. I'm using the Windows Subsystem for Linux (WSL) to get all benefits of Flynt onto my system
2. I have a webserver setup via MAMP native on my Windows machine
3. I can't connect via `mysql --host=localhost --user=USERNAME --password=PASSWORD` because the WSL MySQL socket disallows connections to `localhost` because this is done via the `tcp` protocol.
4. The same command works without problems if I just add `--protocol=tcp` to the command.

The problem with this is, that it's related to the system, not the project you're working on so this setting shouldn't be in the projects **.flynt.json**

What about adding a `.flynt.json` or a `.flynt-global.json` in the users home folder where they can set additional settings like the mysql protocol for example as a global option for flynt?

------

# Screenshot

![image](https://user-images.githubusercontent.com/6538827/27461673-b148c328-57bb-11e7-8cc7-a24931e262dc.png)

**Comment by domtra** [comment]
@dome have you tried `mysql --host=127.0.0.1 --user=USERNAME --password=PASSWORD`? this should work. if so just replace `localhost` with `127.0.0.1` in your `.flynt.json` and `.env`

**Comment by bdbch** [comment]
Yeah `127.0.0.1` just works fine, but if there is a alread existing project I don't want to change the projects `.flynt.json`and `.env` for all other users on the project but only for me.

also adding protocol support wouldn't fix the WP Cli also trying to connect via localhost/127.0.0.1 so maybe we can just create some kind of mapping to overwrite localhost with 127.0.0.1 if needed per user.

**Comment by domtra** [comment]
the easiest thing would be to find out why mysql is looking for the socket in `/var/run/mysql/mysql.sock` and why it is not there. either change your mysql settings or symlink the socket to that location.

**Comment by bdbch** [comment]
I agree this is something which needs to be fixed on my side.
