### ISSUE TITLE
Check accessibility of Composer requirements

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt-cli#62]
So this weekend I had to work on a Flynt project and wanted to set up the project on a computer with no SSH key registered on Github.

If I can remember it was the `flynt-core` package not being able to install without a valid SSH key registered on Github (I guess the required package is installed via SSH instead of HTTPS which triggers this issue).

That means having a Github Account with an SSH key is a requirement right now which shouldn't really be there.

Could've also be a bug on the local computer, but I think I encountered this twice already.

**Comment by Qakulukiam** [comment]
fixed in v0.2.0 (#77)

**Comment by bdbch** [comment]
Thanks!
