### ISSUE TITLE
Remove .env file from .gitignore on create task

### ISSUE THREAD

**Issue by dgrdl** [flyntwp/flynt-cli#7]
We agreed that the .env file should be tracked in a repo, so it should not be ignored in the repo anymore (Bedrock default).

During deployment it will still be excluded.

**Comment by colourgarden** [comment]
@Qakulukiam What was the reasoning behind adding `.env` to the repo rather than relying on `.env.example`? Now forces all developers on a codebase to have identical database and virtual hosts (not necessarily a bad thing but potentially cumbersome to enforce). Also possible security issue with saving salts in source control.

**Comment by domtra** [comment]
The reasoning behind this move was more or less convenience. 
It does force developers to have their local environments set up identically, that is correct. But this brings some additional advantages. We use a workflow with a development server that hosts the source of truth for the db and also upload files. This environment we always clone to our local environment when we start working on something new. From that point on, the db and uploads can diverge. But once a feature is finished and deployed to the development server, it will become the new source of truth again.
Doing so also means that every time we clone from development to local, we have to replace urls and paths in the local database. The information for the adjustments is saved in the `.flynt.json` file. This is also checked into the repo and shared between all developers.
If we did not check in the `.env` and `.flynt.json` files, each developer would have to maintain her own copy which might lead to inconsistencies. 
This technique is only viable for private projects. As you correctly state, this can be a security issue. Not only salts, but also db credentials are stored in the `.env` and `.flynt.json`. For us, this is not a big issue. 1. all our project repos are private, 2. these credentials are only for local and development environments. To access the db, you always have to have ssh access first and sites are basic auth protected.
Sorry for the lengthy description.
If this does not fit your workflow, feel free to remove the files from your repo and add it to your project's `.gitignore`. Use something like `git rm --cached .env && echo '.env' > .gitignore`.
This way, every developer can setup her local environment as she wants.
Feel free to give us additional feedback and please tell us how you proceed.

**Comment by Qakulukiam** [comment]
@domtra Do you think passing an option to the CLI, e.g. `flynt create --public` or `flynt create -p`, which does not remove `.env` from `.gitignore` and adds `.flynt.json`, would be a possible fix for this?

**Comment by colourgarden** [comment]
Thanks @domtra, @Qakulukiam for your quick and detailed replies :)

> If we did not check in the .env and .flynt.json files, each developer would have to maintain her own copy which might lead to inconsistencies.

Storing `.env.example` in source control (Bedrock default) with the relevant shared settings would also achieve this. It would then just require the developer to `cp .env.example .env` upon first installation. Same solution could be used with `.flynt.json.example` (this is how we've set our own project up so far).

CLI option would also be good 👍
